# -*- coding: utf-8 -*-
"""test combat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZ65Bf1oTwXcpSBRl_tTUzlMSSq5_6gA
"""

def About():
    print("Le jeu s'inspire de la pendémie actuel qui est parti de Chine du Coronavirus qui\n"
          "touche la france et le monde entier depuis le mois de janvier 2020 jusqu'à aujourd'hui\n"
          "et qui a fait plus de 95 millions de contamination et 2 millions de mort dans le monde entier\n"
          "vous jouez un docteur de trouver un vaccin contre le Coronavirus.\n"
          "le jeu à été fait par :\n Yasmina Hadjar\n Cyril Gable\n Noham Hirep\n Andres Lopez Morales")


import random
def Coronaventure(nom):
  print("\n\n\n")
  print(" ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ██╗ █████╗ ██╗   ██╗███████╗███╗   ██╗████████╗██╗   ██╗██████╗ ███████╗")
  print("██╔════╝██╔═══██╗██╔══██╗██╔═══██╗████╗  ██║██╔══██╗██║   ██║██╔════╝████╗  ██║╚══██╔══╝██║   ██║██╔══██╗██╔════╝")
  print("██║     ██║   ██║██████╔╝██║   ██║██╔██╗ ██║███████║██║   ██║█████╗  ██╔██╗ ██║   ██║   ██║   ██║██████╔╝█████╗  ")
  print("██║     ██║   ██║██╔══██╗██║   ██║██║╚██╗██║██╔══██║╚██╗ ██╔╝██╔══╝  ██║╚██╗██║   ██║   ██║   ██║██╔══██╗██╔══╝  ")
  print("╚██████╗╚██████╔╝██║  ██║╚██████╔╝██║ ╚████║██║  ██║ ╚████╔╝ ███████╗██║ ╚████║   ██║   ╚██████╔╝██║  ██║███████╗")
  print(" ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝")
  import time
  time.sleep(2)
  Menu(nom)

def Menu(nom):
  print("\n\n\n")
  print(" _____________________________")
  print("   \                             \ ")
  print("|   |                            |")
  print(" \_ |            MENU            |")
  print("    |                            |")
  print("    |                            |")
  print("    |      [1] Create New Game   |")
  print("    |                            |")
  print("    |                            |")
  print("    |      [2] About             |")
  print("    |                            |")
  print("    |                            |")
  print("    |      [3] Exit              |")
  print("    |                            |")
  print("    |                            |")
  print("    |   _________________________|___")
  print("    |  /                            /")
  print("    \_/____________________________/")
  Choix = int(input())
  if Choix == 1:
    NewGame(nom)
  elif Choix == 2:
    About()
  else:
    print("Fermeture du jeu")
    import time
    time.sleep(2)
    quit()
    

def About() :
  print("Le jeu s'inspire de la pandémie actuel du Coronavirus qui est partie de Chine et qui\n"
          "touche la France et le monde entier depuis le mois de janvier 2020 jusqu'à aujourd'hui.\n"
          "Elle a fait plus de 95 millions de contaminations et 2 millions de morts dans le monde entier.\n"
          "Vous jouez un docteur dont la mission est de trouver un vaccin contre le Coronavirus.\n"
          "\n"
          "Le jeu à été fait par :\n Yasmina Hadjar\n Cyril Gable\n Noham Hirep\n Andres Lopez Morales")
  
def NewGame(nom) :
  AskName(nom)

def AskName(nom):
  a = ", comme tu le sais depuis plus d’un an le monde\n fait face à une menace invisible, une pandémie d’un virus appelé Covid-19.\n \n Le virus se serait échappé de la ville de Wuhan en Chine\n et sévit aujourd’hui dans le monde entier.\n Le nombre de contaminés augmente de jour en jour et provoque des milliers de morts. \n\n Les gouvernements tentent de l'endiguer par des mesures restrictives,\n et à vrai dire, elles ne sont pas respectées. \n\n Tu pourras t’en rendre compte au cours de ta mission.\n Nous avons besoin de toi pour mettre fin à cette épidémie, mais tu n’es pas seul.\n Rend toi à Marseille, Le Professeur Raoult t'y attend, \n il te guidera lors de ton aventure à travers le monde.\n \n Pour surmonter cette épreuve, n'oublie pas de bien porter ton \n masque sur le nez et d’éviter les contacts pour te protéger du virus. "
  print("\n\n\nQuel est ton nom de Docteur: ")
  Name = nom
  print("\n\n Bienvenue Docteur", Name,a,"\n\n\n")
  import time
  time.sleep(3)
  avion()
 

def avion():
  import time
  time.sleep(1)
  print("                                                   ___")
  print("                                                    \\ \ ")
  print("                                                     \\ `\ ")
  print("                                  ___                 \\  \ ")
  print("                                 |    \                \\  `\ ")
  print("                                 |_____\                \    \ ")
  print("                                 |______\                \    `\ ")
  print("                                 |       \                \     \ ")
  print("                                 |      __\__---------------------------------._.")
  print("                               __|---~~~__o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_[][\__")
  print("...---------------------------|___                         /~      )                \__")
  print("                                  ~~~---..._______________/      ,/_________________/")
  print("                                                         /      /")
  print("                                                        /     ,/")
  print("                                                       /     /")
  print("                                                      /    ,/")
  print("                                                     /    /")
  print("                                                    //  ,/")
  print("                                                   //  /")
  print("                                                  // ,/")
  print("                                                 //_/ ")
  import time
  time.sleep(1)

  
def Debut():
    print("\n\n\n Te voilà maintenant en France, à Marseille, va rejoindre le Professeur Raoult")
    print(" [1]Rejoindre\n [2]Quitter")
    choix = int(input())
    if choix == 1 :
      print(" Te voilà, nous avons besoin de toi. Le virus continue de circuler massivement malgré les restrictions, il va falloir les faire respecter.\n Je compte sur toi. Il faudra également détruire le virus à sa source.\n Je suis en train de mettre au point un vaccin anti-Covid, je t'appellerai dès qu'il sera prêt.\n  Ta mission sera longue, tu vas traverser le monde et rencontrer toutes sortes de détraqués, malades... \n Bonne chance, protège-toi bien et n'hesite pas à me demander de l'aide si besoin.")
    elif choix == 2 :
      print("Fermeture du jeu")
      import time
      time.sleep(2)
      quit()



def Map(D,x,y):
  map = [ [0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0] ]
  map[y][x] = 1
  if D == 1 and y != 1:
    map[y][x] = 0
    y = y - 1
    map[y][x] = 1
  elif D == 2 and y != 3:
    map[y][x] = 0
    y = y + 1
    map[y][x] = 1
  elif D == 3 and x == 3 and y == 1 or y == 2:
    print("")
    print(" Tu ne peux pas te rendre à cette destination (Chine), la Covid-19 y est trop forte, trouve un autre itinéraire.")
    print(" (Sélectionnez une autre direction) ")
  
  elif D == 3 and x != 4:
    map[y][x] = 0
    x = x + 1
    map[y][x] = 1
  elif D == 4 and x != 1:
    map[y][x] = 0
    x = x - 1
    map[y][x] = 1
  else:
    print("")
    print(" /!\/!\/!\ Vous avez atteint la limite de la map /!\/!\/!\ ")
    print(" (Sélectionnez une autre direction) ")
  print("")
  for row in map:
      print(row)





def Movement (x,y,Mouv):
  if Mouv == 1:
    print(" Vous vous déplacez vers le Nord ")
    Map(1,x,y)
  elif Mouv == 2:
    print(" Vous vous déplacez vers le Sud ")
    Map(2,x,y)
  elif Mouv == 3:
    print(" Vous vous déplacez vers l'Est ")
    Map(3,x,y)
  elif Mouv == 4:
    print(" Vous vous déplacez vers l'Ouest ")
    Map(4,x,y)
  else:
    print(" /!\/!\/!\ Erreur de synthaxe, réessayez /!\/!\/!\ ")





def X_add(x):

  if x == 1:
    return 0
  if x == 2:
    return 0
  if x == 3:
    return 1
  if x == 4:
    return -1





def Y_add(y):
  if y == 1:
    return -1
  if y == 2:
    return 1
  if y == 3:
    return 0
  if y == 4:
    return 0





def Event (nom,x,y,Fin_Marseille,Fin_Paris,Fin_Londres,Fin_Stockholm,Fin_AeroportCDG,Fin_Washington,
    Fin_LosAngeles,Fin_Cancun,Fin_Rome,Fin_Taiwan,Fin_Chine1,Fin_Chine2):
    if x==2 and y==3:
      print("")
      Marseille(Fin_Marseille)
    elif x==2 and y==2: 
      print("")
      Paris(Fin_Paris)
    elif x==2 and y==1:
      print("")
      Londres(Fin_Londres)
    elif x==3 and y==1:
      print("")
      Stockholm(Fin_Stockholm)
    elif x==1 and y==1:
      print("")
      Washington(Fin_Washington)
    elif x==1 and y==2:
      print("")
      LosAngeles(Fin_LosAngeles)
    elif x==1 and y==3:
      print("")
      Cancun(Fin_Cancun)
    elif x==3 and y==3:
      print("")
      Rome(Fin_Rome)
    elif x==4 and y==3:
      print("")
      Taiwan(Fin_Taiwan)
    elif x==4 and y==2:
      print("")
      Shanghai(Fin_Shanghai)
    elif x==4 and y==1:
      print("")
      Wuhan(nom,Fin_Wuhan)
    elif x==3 and y==2:
      print("")
      CDG(Fin_CDG)





def Deplacement(x,y):
  print("")
  print("Choisis ta direction :")
  print("1: Nord")
  print("2: Sud")
  print("3: Est")
  print("4: Ouest")
  Mouv = int(input())
  print("---------------------------")
  print("")
  Movement(x,y,Mouv)  
  print("")
  print("---------------------------")
  return Mouv





def ResultatY(x,y,Mouv):
  if Mouv == 1:
    if y != 1:
      y = y + Y_add(Mouv)
      return y
    else: 
      return y
  elif Mouv == 2:
    if y != 3:
      y = y + Y_add(Mouv)
      return y
    else: 
      return y
  else:
    y = y + Y_add(Mouv)
    return y

def ResultatX(x,y,Mouv):
  if Mouv == 3: 
    if x == 3 and y == 1 or y == 2:
      return x
    elif x != 4:
      x = x + X_add(Mouv)
      return x
    else: 
      return x
  elif Mouv == 4:
    if x != 1:
      x = x + X_add(Mouv)
      return x
    else: 
      return x
  else:
    x = x + X_add(Mouv)
    return x








def Paris(Fin_Paris):
  if Fin_Paris == 0:
    print("C'est votre première fois à Paris")
    print("Tu es dans les rues de la ville de Paris et, soudain, tu rencontres des coureurs ! Tu dois te battre contre eux afin de faire respecter le confinement.")
    CombatCoureurs()
  else: 
    print("Vous êtes déjà passé à Paris, il n'y a plus rien à faire.")
    print("")

def Marseille(Fin_Marseille):
  if Fin_Marseille == 0:
    Debut()


  else: 
    print("Vous êtes déjà passé à Marseille, il n'y a plus rien à y faire.")
    print("")

def Londres(Fin_Londres):
  if Fin_Londres == 0:
    print("C'est votre première fois à Londres")
    print("Tu entres dans un magasin à Londres où une émeute a été provoquée, à toi de régler le probleme à ta façon.")
    CombatPQ()
  else: 
    print("Vous êtes déjà passé à Londres, il n'y a plus rien à y faire.")
    print("")

def CDG(Fin_CDG):
  if Fin_CDG == 0:
    print("C'est votre première fois à l'aéroport Charles de Gaulle")
    print("Te voici à l'aéroport Charles de Gaulle. Oh ! Une boutique duty free ! Parfait, tu vas pouvoir acheter pleins de choses utiles :)")
    Boutique()
  else: 
    print("Vous êtes déjà passé à l'aéroport Charles de Gaulle, il n'y a plus rien à y faire.")
    print("")

def LosAngeles(Fin_LosAngeles):
  if Fin_LosAngeles == 0:
    print("C'est votre première fois à Los Angeles")
    print("C'est le mauvais moment pour te balader dans les rues de Los Angeles, une foule de manifestants te bloquent le passage. Confine les à ta manière ;)")
    CombatManifestants()
  else: 
    print("Vous êtes déjà passé à Los Angeles, il n'y a plus rien à y faire.")
    print("")

def Rome(Fin_Rome):
  if Fin_Rome == 0:
    print("C'est votre première fois à Rome")
    print("Te voici dans les rues de Rome, ça alors, des vieux tentent de s'enfuir d'un EHPAD. ... Quand faut y aller.")
    CombatVieux()
  else: 
    print("Vous êtes déjà passé à Rome, il n'y a plus rien à y faire.")
    print("")

def Taiwan(Fin_Taiwan):
  if Fin_Taiwan == 0:
    print("C'est votre première fois à Taiwan")
    print("Te voici à Taiwan, tu entres dans une boutique au catalogue impressionnant !.")
    Boutique()
  else: 
    print("Vous êtes déjà passé à Taiwan, il n'y a plus rien à y faire.")
    print("")

def Shanghai(Fin_Shanghai):
  if Fin_Shanghai == 0:
    print("C'est votre première fois à Shanghai")
    print("Tu viens d'arriver en Chine, à Shanghai. Tu as retrouvé et t'apprêtes à te battre contre Le Patient 0, Protège-toi bien, tout devrait se terminer ici. ")
    CombatsPatient()
  else: 
    print("Vous êtes déjà passé à Shanghai, il n'y a plus rien à y faire.")
    print("")

def Wuhan(nom,Fin_Wuhan):
  if Fin_Wuhan == 0:
    print("C'est votre première fois à Wuhan")
    CombatsPangolin()
    fin(nom)

  else: 
    print("Vous êtes déjà passé à Wuhan, il n'y a plus rien à y faire.")
    print("")


def Stockholm(Fin_Stockholm):
  if Fin_Stockholm == 0:
    print("À votre avis, à quelle distance doit-on être d'autrui pour respecter la distanciation sociale ?")
    print("1: 10cm")
    print("2: 50cm")
    print("3: 1m50")
    print("4: 10m")
    R = int(input())
    if R == 3:
        print("Bonne réponse, tu as gagné ")
    else:
        print("Mauvaise réponse")
  else:
    print("vous êtes déjà passé à Stockholm, il n'y a plus rien à y faire.")

def Washington(Fin_Washington):
  if Fin_Washington == 0:
    print("À votre avis quelle est la meilleure facon de lutter contre le virus ?")
    print("1: S'injecter du gel hydroalcoolique ( d'après Trump )")
    print("2: S'injecter du soleil ( encore lui mdr")
    print("3: Respecter les mesures et se vacciner.")
    print("4: Continuer de vivre, de toute facon ça n'est qu'une grosse grippe.")
    R = int(input())
    if R == 3:
        print("Bonne réponse tu as gagné " )
    else:
        print("Mauvaise réponse")
  else:
    print("vous êtes déjà passé à Washington, il n'y a plus rien à y faire.")

def Cancun(Fin_Cancun):
  if Fin_Cancun == 0:
    print("Des amis vous proposent de venir faire la fête sur la plage, il y a beaucoup de monde et de boissons.")
    print("1: Avec plaisir, je peux bien m'accorder ce moment de détente..")
    print("2: Non navré, la distanciation sociale n'est pas respectée et j'ai une mission qui m'attend !")
    R = int(input())
    if R == 2:
        print("Bonne réponse tu as gagné ")
    else:
        print("Mauvaise réponse")
  else: 
    print("vous êtes déjà passé à Cancun, il n'y a plus rien à y faire.")
        










def Gameisnotfinished(Game):
  if Game == 0:
    return True
  elif Game == 1:
    return False






#MEDICAMENTS
def medoc():
  medoc = ['doliprane (+10pv)', 'advil (+5pv)', 'efferalgant (+20pv)', 'sirop + (1pv)']
  medocrand = random.randint(0,3)
  medocdrop = medoc[medocrand]
  return medocdrop

#TOUT CE QU'ON PEUT ACHETER
achetable = {}
achetable ["[1]Gel 100% (Il s'agit d'une amélioration du gel 50%)\n"]= 27,
achetable ["[2]Fourmis ( Des fourmis ??? Qui sait ca peut sûrement servir)\n"] = 2,
achetable ["[3]Masque FFP2 ( Il s'agit d'une amélioration du foulard/masque chirurgical)\n"] = 15,
achetable ["[4]Medoc ( Distribués de facon aléatoire, tu as la possibilité d'avoir : Advil, Doliprane, Efferalgant, Sirop)\n"] = 10 ,
achetable ["[5]Gants vinyle ( Il s'agit d'une amélioration des gants)\n"] = 15

#LISTE INVENTAIRE
inventaire = ["foulard","gel 50%","blouse"]

#INVENTAIRE
def invent():
  print("INVENTAIRE :\n\n Voici ton inventaire :","\n")
  for i in inventaire : 
    print(i)

#BOUTIQUE
def Boutique():
  print("\n\n     BOUTIQUE\n\n\n Que souhaitez vous acheter?\n\n\n")
  for i in achetable :
    print(i)
  print(Pieces())
  print("[6]Exit")
  choix = int(input())
  if choix == 1 :
    print("Cet article coûte",achetable["[1]Gel 100% (Il s'agit d'une amélioration du gel 50%)\n"],"pieces","\nVoulez vous l'acheter?","(oui/non)")
    ouinon = str(input())
    if ouinon == "oui" :
      inventaire.append("Gel 100%")
      print("\nTu as un nouvel item dans ton inventaire\n\n")
      invent()
    if ouinon == "non" :
      Boutique()
    else :
      Boutique()
  elif choix == 2 :
    print("Cet article coûte",achetable["[2]Fourmis ( Des fourmis ??? Qui sait ca peut sûrement servir)\n"],"pèces","\nVoulez vous l'acheter?","(oui/non)")
    ouinon = str(input())
    if ouinon == "oui" :
      inventaire.append("Fourmis")
      print("\nTu as un nouvel item dans ton inventaire\n\n")
      invent()
    if ouinon == "non" :
      Boutique()
    else :
      Boutique()
  elif choix == 3 :
    print("Cet article coûte",achetable["[3]Masque FFP2 ( Il s'agit d'une amélioration du foulard/masque chirurgical)\n"],"pièces","\nVoulez vous l'acheter?","(oui/non)")
    ouinon = str(input())
    if ouinon == "oui" :
      inventaire.append("Masque FFP2")
      print("\nTu as un nouvel item dans ton inventaire\n\n")
      invent()
    if ouinon == "non" :
      Boutique()
    else :
      Boutique()
  elif choix == 4 :
    print("Cet article coûte",achetable["[4]Medoc ( Distribués de facon aléatoire, tu as la possibilité d'avoir : Advil, Doliprane, Efferalgant, Sirop)\n"],"pièces"," vous receverez 1 médicament aléatoire\nVoulez vous l'acheter?","(oui/non)")
    ouinon = str(input())
    if ouinon == "oui" :
      inventaire.append(medoc())
      print("\nTu as un nouvel item dans ton inventaire\n")
      invent()
    if ouinon == "non" :
      Boutique()
    else :
      Boutique()
  elif choix == (5) :
    print("Cet article coûte",achetable["[5]Gants vinyle ( Il s'agit d'une amélioration des gants)\n"],"pieces","\nVoulez vous l'acheter?","(oui/non)")
    ouinon = str(input())
    if ouinon == "oui" :
      inventaire.append("Gants vinyle")
      print("\nTu as un nouvel item dans ton inventaire\n\n")
      invent()
    if ouinon == "non" :
      Boutique()
    else :
      Boutique()
  elif choix == 6 :
    print("Retour au jeu")
  else :
    Boutique()





# -------------------------------messages de fin----------------------------------
# une fois fourmis données : frappé ?/ amadouer ? //// capturer/soigner /// tuer //// si tuer ==> perdu /// si capturer/soigner ===>>> bien vu 
#print("\n\nDevenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
#print("Tu as fini ta mission, enfin, le monde en a fini de cette pandémie. Bravo! Rejoint D.Raoult, il a un message pour toi.")
#print("")


# ----------------------------Pièces-----------------------------------------------
def Pieces():
    pieces = [10]
    print("Porte-feuille :", pieces)

# --------------------------------------------------------Question-Covid-----------------------------------------------------------------------
def CompteurQuestion(c):
  c = c + 1
  if c == 3 :
    invent.append("Vaccin")


def QuestionStockholm():
    print("À votre avis, à quelle distance doit-on être d'autrui pour respecter la distanciation sociale ?")
    print("1: 10cm")
    print("2: 50cm")
    print("3: 1m50")
    print("4: 10m")
    R = int(input())
    if R == 3:
        print("Bonne réponse, tu as gagné ")
        CompteurQuestion(c)
    else:
        print("Mauvaise réponse")
        QuestionStockholm()
def QuestionWashington():
    print("À votre avis quelle est la meilleure facon de lutter contre le virus ?")
    print("1: S'injecter du gel hydroalcoolique ( d'après Trump )")
    print("2: S'injecter du soleil ( encore lui mdr")
    print("3: Respecter les mesures et se vacciner.")
    print("4: Continuer de vivre, de toute facon c'est qu'une grosse grippe.")
    R = int(input())
    if R == 3:
        print("Bonne réponse tu as gagné " )
        CompteurQuestion(c)
    else:
        print("Mauvaise réponse")
        QuestionWashington()
def QuestionCancun():
    print("Des amis vous proposent de venir faire la fête sur la plage, il y a beaucoup de monde et de boissons")
    print("1: Avec plaisir, je peux bien m'accorder ce moment de détente..")
    print("2: Non navré, la distanciation sociale n'est pas respectée et j'ai une mission qui m'attend !")
    R = int(input())
    if R == 2:
        print("Bonne réponse tu as gagné ")
        CompteurQuestion()
    else:
        print("Mauvaise réponse")
        QuestionCancun()

# --------------------------------Combats---------------------------------------------------

def Kappa():
    import time
    time.sleep(2)
    print("\n\n\n")
    print("                                         `.::.`     ```..``                            ")             
    print("                                     `` .+ssoosys+/+o+oss+/--::``..                    ")               
    print("                                      +ooso:--/ossoo+/::++//+o++oooo:.`                ")               
    print("                               .+oo+/ossso/:/+//:///://:oo/++o/+s+ossso.               ")               
    print("                            `:osyyoss//yy++oo//++++++o++so+/+--:++osssyy+-`            ")               
    print("                          .:shsyyoyso+yyyyyoooosoo+++oo+o/--+.-:oso+//////:-``         ")               
    print("                       `/yhyhyysoyysoshhhys+/oso/:::-..::.`-/../o+::--.``.`--/.        ")               
    print("                      -ydhssyssosyyooyss+///os+-:/:.```..`..:../---:::-``...--:.       ")               
    print("                     -dmhyssyysysyo+sooooo++/::-::-.:.....--/-:-..-:/:.` `  `.-/`      ")               
    print("                     sdhysysyyyooo//++oo/:/:.-`--/--::..-::///:-...-:.``     `:-`      ")               
    print("                     yyysyyysoo++/:/::-..---..`..-:::--:::++oo++::-...`````   ..       ")               
    print("                    .ysysyyoo++-/-..````...-.````-:://+oossyyyyysso+::-.````   --      ")               
    print("                    oooooo+++::.-`` ````.----.-..::+osyhhhhhdhhhhyyyso/:`      `-      ")               
    print("                   .o://:+//-....  `  `---:////:/ossyhddddddddhhhhhhhys+:.     `-      ")               
    print("                   ./-:-::-.```.`    `...-/++++/ohhhddmmdddddhhhhhhhyyso+/.   `:.      ")               
    print("                   `/.----.`` `.  ``..--/+ohhhysshdhdmmddddhdhhhhhhyyyssso+. ``--      ")               
    print("                    :--...` ``.`` .:-/:/+++syhddyhddmmmddddhhhhhhhhyyysssss/`  `.      ")               
    print("                    .:-.`` ``````-+o++ooohhhyhdmmdddmmmdddhddhhdhhhhhyyyssso-` ``      ")               
    print("                    `/.``  ` ``.-//+oshddddmmmmmmmmmmmmddhhdhhdddddhhyyyssso/````      ")               
    print("                     :.``  ```..-:+syddmmmmmmmmmmmmddhhhhhhhhhdhhhyyyssssssso` `       ")                
    print("                     /+-.   ``.:ohmmmmmmdddhyso++/--:::/+osyyso+:--.....----+/:        ")               
    print("                    :mddy-``..:+dmmmmmdhyso+++/:-...-::/+oyddy+-.`` ``.`.-::+o/        ")               
    print("                    :h++sso:.-:smmmmmmdhys+//:/:/:+///ossyhmmms:-:::--:---/+os+        ")               
    print("                    `dsydhyo::/ymmmmNNNmmddhhyssoooo+oshhddmNmdo++++++/++oosyy:        ")              
    print("                     hhhdyo+ss+ydmmmmNNNNNNNmmdhhhyyhdddddmmNNmyoooooosssssyys:        ")               
    print("                     -hddyyhmNdmmmmmmmNNNNNNNNNmmmmmmmddmmmmNNmdsssyyyyyyyyyss:        ")               
    print("                      .hmddmmNmmmddmmmmmmmNNNNNNNNNNNmddmmmmNNNmhssyhhhhhyysoo-        ")              
    print("                       .hmNNmNNmdddmmmmmmmmmmmmmmmddhhdmmNmmNNmdhyyssyyyyssoo+.        ")               
    print("                        :NNNNNmmdmmmmmmddddddddhhhyyhyddhdmddmdhyssoossssoo+++.        ")               
    print("                        `mNNNNmmmmmmmmddddhhhhhyyyyhddhs+/++osso+//+oooooo++++`        ")               
    print("                         -syyyddddmdmmdddddhhhyyyhddmdddhyyso+/:::+ooosooooo+/         ")              
    print("                          `.``+dhddddddddddddhhhddddddhhhyyyso++//++oosssso++.         ")               
    print("                              `yhhdddddddddddddddhyyyyyyyyssoo++////+osyyso+/          ")               
    print("                               .yyyhhhhhhdddddddhysssssso+///::::::+osyys+++.          ")              
    print("                                .syyyyyhhhhhhhhhhdmmmddhhyysssoooosssooo++/.           ")               
    print("                                 .+sssyyyyyysssyhdmmdddhyysoo+oooosso++///.            ")              
    print("                                   ./osssssssssyhhdddhhyyyssoooooosoo+//:`             ")               
    print("                                     ./oosssssyyhhhhhhhhhyyyysssssso+/:.               ")               
    print("                                       `-+oosssyyyyhhdddddhhyyyyyys+/-                 ")               
    print("                                          .:+oossssssyyyyyyssssoo+/-`                  ")               
    print("                                             `-:/+++++++++++++//:-`                    ")               
    print("                                                  ````.......```                       ")              
    print("\n\n\n")




import random

class joueur (object) :
    nom = "nom"
    pv = 50
    maxpv = 50
    pièces = Pieces()


class Vieux (object):
    nom = " Ennemi : Vieux évadés d'EPHAD\n"
    pv = 6
    attaque = "Attaque : Non respect de la distanciation sociale\n"


class Coureurs (object) :
    nom = " Ennemi : soi-disant 'sportifs'\n"
    pv = 15 
    attaque ="Attaque : Non respect du confinement\n"


class PQ (object) :
    nom =" Ennemi : Émeutiés dans un magasin pour acheter du PQ\n"
    pv = 6
    attaque ="Attaque : Lancé de PQ\n"


class Manifestants (object) :
    nom = " Ennemi : Manifestants américains\n"
    pv = 20
    attaque ="Attaque : Coups de pancartes\n"


class Patient (object) :
    nom ="Ennemi : Le Patient 0\n"
    pv = 70
    attack = "Attaque :[1]Toux / [2]Vomis" 
 

def Patien():
    attaque = ["Toux","Vomis"]
    attaqueChance = random.randint(0,1)
    attaqueDrop = attaque[attaqueChance]
    print(attaqueDrop)
    return attaqueDrop


class Pangolin (object) :
    nom =" Ennemi : Pangolin\n"
    pv = 150
    attack = "Attaque : [1] Griffure /[2] Morsure /[3] Roulade\n"
    info = "Info supplémentaires : Le pangolin, grâce à ses écailles robustes, ne craint pas les piqures, doté de longues griffes il est capable d'infliger de nombreux dégats. De plus, il est porteur du virus ! "


def Pango():
    attaque = ["Morsure","Griffure","Roulade"]
    attaqueChance = random.randint(0,2)
    attaqueDrop = attaque[attaqueChance]
    print(attaqueDrop)
    return attaqueDrop

def fin(nom) :
  print("Tu as fini ta mission, enfin, le monde en a fini de cette pandémie. Bravo! Rejoint D.Raoult, il a un message pour toi.")
  print("Raoult : Bravo à toi","Docteur",nom," ! tu as detruit le virus, la pandemie devrait prendre fin d'ici peut... Le problème c'est que le virus à muté, c'est reparti.")
  import time
  time.sleep(30)
  quit()

class arme (object):
    #combats vieux
    vieuxcoup= 2
    vieuxgel = 0
    vieuxgel1 = 1
    vieuxvaccin = 6
    #combats pangolin
    pangolincoup =  5
    pangolingel = 1
    pangolingel1 = 1
    pangolinvaccin = 0
    pangolinfourmis = 150
    #combat patien
    patientcoup = 5
    patientgel = 10
    patientgel1 = 17
    patientvaccin = 20
    #combat manifestants
    manifestantscoup = 10
    manifestantsgel = 5
    manifestantsgel1 = 7
   
    #combat pq
    pqcoup = 3
    pqgel = 1
    #combat courreur
    coureurscoup= 10
    coureursgel = 5

class degat (object):

    vieuxattaque = 2
    pqlance = 5
    manifestantsattaque = 3
    coureursattaque = 2
    pangolingriffure = 10
    pangolinmorsure = 10
    pangolinroulade = 20
    patienttoux = 10
    patientvomis = 20
   


def CombatVieux() : 
  print("Raoult a mis au point un vaccin, tu as un nouvel item dans ton inventaire")
  print("Attention ! Des vieux se sont échappés des EPHAD, ils approchent ne les laisses surtout pas te toucher. n'oublies pas les 1m de distance.\nVoici leurs caractéristiques: \n")
  print(Vieux.nom, "PV :", Vieux.pv,"\n", Vieux.attaque)
  while Vieux.pv > 0 :
        print("\n\nDes vieux t'approchent de trop près ! \n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n [3] Gel hydroalcoolique 100%\n [4] Vaccin ")
        choice = int(input())
        if choice == 1 :
            Vieux.pv = Vieux.pv - arme.vieuxcoup
            print("PV ennemi :", Vieux.pv,"\nTon attaque est efficace mais pas conseillé, protèges tes anciens")
            print("De plus, ils répliquent, tu as reçu un coup en retour ")
            joueur.pv = joueur.pv - degat.vieuxattaque
            print("et tu as perdu ",degat.vieuxattaque,"PV\n""tes PV :",joueur.pv)
        if choice == 2 : 
            Vieux.pv = Vieux.pv - arme.vieuxgel
            print("PV ennemi :", Vieux.pv, "\nCette attaque est inefficace, ils ont reussit a te toucher ")
            joueur.pv = joueur.pv - degat.vieuxattaque 
            print("tes PV :",joueur.pv)
        if choice == 3 :
            Vieux.pv = Vieux.pv - arme.vieuxgel1 
            print("PV ennemi :", Vieux.pv, "\nCette attaque n'est pas très efficace, ils ont reussit a te toucher ")
            joueur.pv = joueur.pv - degat.vieuxattaque 
        if choice == 4 :
            Vieux.pv = Vieux.pv - arme.vieuxvaccin
            print("PV ennemi :", Vieux.pv, "\nBien joué tu as vacciné les vieux, ils sont désormais inoffensifs !")
            print("Tu as gagngé une récompense : +20 pièces")
        if joueur.pv <= 0 : 
            print("\n\n\n\n\n\n")
            print("tu as été infecté, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit()
  else : 
       print("Tu as gagné ce combat")       

def CombatCoureurs() : 
  print("Depuis le confinement, les parisiens sont devenus de grands athlètes, les rues sont bondées de neo-sportifs. Et malgré leur tenue pro tu n'auras surement pas de mal à faire respecter les mesures gouvernementales.\n")
  print("Voici leurs caractéristiques : \n")
  print(Coureurs.nom, "PV :", Coureurs.pv,"\n", Coureurs.attaque)
  while Coureurs.pv > 0 :
        print("\n\nLes parisiens se prenent pour des athletes de haut niveau, fais respecter le confinement ! \n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n ")
        choice = int(input())
        if choice == 1 :
            Coureurs.pv = Coureurs.pv - arme.coureurscoup
            print("PV ennemi :", Coureurs.pv,"\nTon attaque est très efficace, ils sont rentrés chez eux. ")
        if choice == 2 : 
            Coureurs.pv = Coureurs.pv - arme.coureursgel
            print("PV ennemi :", Coureurs.pv, "\nCette attaque n'est pas très efficace, ils ont reussit à te toucher ")
            joueur.pv = joueur.pv - degat.coureursattaque 
            print("tes PV :",joueur.pv)
            print("Tu as gagngé une récompense : +10 pièces")
        if joueur.pv <= 0 : 
            print("\n\n\n\n\n\n")
            print("tu as été infecté, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit()
  else :
        print("Tu à gagné ce combat")

def CombatPQ() :
  print("Tu es entré dans un magasin rempli de fous furieux... une émeute a été provoquée à cause d'une pénurie de PQ. Tu vas devoir les calmer, pas la peine de prendre des pincettes.\n")
  print("Voici leurs caractéristiques : \n")
  print(PQ.nom, "PV :", PQ.pv,"\n", PQ.attaque)
  while PQ.pv > 0 :
        print("\n\nLes déséquilibrés du magasin s'appretent à te lancer du pq  \n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n ")
        choice = int(input())
        if choice == 1 :
            PQ.pv = PQ.pv - arme.pqcoup
            print("PV ennemi :", PQ.pv,"\nTon attaque est très efficace ")
        if choice == 2 : 
            PQ.pv = PQ.pv - arme.pqgel
            print("PV ennemi :", PQ.pv, "\nCette attaque n'est pas très efficace, ils ont reussit à te toucher ")
            joueur.pv = joueur.pv - degat.pqlance
            print("tes PV :",joueur.pv)
            print("Tu as gagngé une récompense : +15 pièces")
        if joueur.pv <= 0 : 
            print("\n\n\n\n\n\n")
            print("tu as été assomé, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit()
  else :
        print("Tu à gagné ce combat, ils ont reposé le pq à sa place et ont compris qu'il n'y a pas de pénurie.")     

def CombatManifestants() :
  print("Tu es aux États-Unis...il fallait s'y attendre. Te voilà face à des manifestants ANTI-MesureCovid. Ne t'en fais pas ils ne sont pas très coriaces.\n")
  print("Voici leurs caractéristiques : \n")
  print(Manifestants.nom, "PV :", Manifestants.pv,"\n", Manifestants.attaque)
  while Manifestants.pv > 0 :
        print("\n\nLes manifestants s'appretent à te frapper à coup de pancartes\n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n [3] Gel hydroalcoolique 100%\n ")
        choice = int(input())
        if choice == 1 :
            Manifestants.pv = Manifestants.pv - arme.manifestantscoup
            print("PV ennemi :", Manifestants.pv,"\nTon attaque est très efficace ")
        if choice == 2 : 
            Manifestants.pv = Manifestants.pv - arme.manifestantsgel
            print("PV ennemi :", Manifestants.pv, "\nCette attaque n'est pas très efficace, ils ont reussit à te frapper ")
            joueur.pv = joueur.pv - degat.manifestantsattaque
            print("tes PV :",joueur.pv)
        if choice == 3 :
            Manifestants.pv = Manifestants.pv - arme.manifestantsgel1
            print("PV ennemi :", Manifestants.pv, "\nCette attaque est efficace")
            joueur.pv = joueur.pv - degat.manifestantsattaque
            print("Tu as gagngé une récompense : +20 pièces")
        if joueur.pv <= 0 : 
            print("\n\n\n\n\n\n")
            print("tu as été assomé, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit()
  else :
        print("Tu à gagné ce combat, ils sont rentrés se confiner")       

def CombatsPatient() :
    print("Le voilà... Celui qui est à l'origine de tout ce bordel. Bat le Patient 0 pour en finir avec cette pandémie et retrouver une vie normale !\n")
    print("Voici ses caractéristiques :\n")
    print(Patient.nom, "PV :", Patient.pv,"\n",Patient.attack)
    while Patient.pv > 0 :
        print("\n\nLe Patient 0 s'apprete a t'attaquer avec : ")
        Patien()
        print("\n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n [3] Gel hydroalcoolique 100%\n [4] Vaccin")
        choice = int(input())
        if choice == 1 :
            Patient.pv = Patient.pv - arme.patientcoup
            print("PV ennemi :", Patient.pv,"\nTon attaque n'est pas très efficace, il a reussit à te toucher")
            joueur.pv = joueur.pv - degat.patienttoux
            print("tes PV :",joueur.pv)
        if choice == 2 : 
            Patient.pv = Patient.pv - arme.patientgel
            print("PV ennemi :", Patient.pv, "\nCette attaque n'est pas très efficace, il a reussit à te toucher")
            joueur.pv = joueur.pv - degat.patientvomis
            print("tes PV :",joueur.pv)
        if choice == 3 :
            Patient.pv = Patient.pv - arme.manifestantsgel1
            print("PV ennemi :", Patient.pv, "\nCette attaque est efficace, ")
        if choice == 4 :
            Patient.pv = Patient.pv - arme.patientvaccin
            print("PV ennemi :", Patient.pv, "\n Cette attaque est très efficace, tu as reussit à le vacciner")
            print("Tu as gagngé une récompense : +40 pièces")
        if joueur.pv <= 0 : 
            print("\n\n\n\n\n\n")
            print("tu as été infecté, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit()
    else :
        print("")
        print("Tu à gagné ce combat, le Patient 0 n'est plus une menace.\nCa y est, tu as anéanti le virus à sa source ! Tu peux enfin respirer sans crainte :D ")


def CombatsPangolin() :
    Kappa()
    print("C'est pas fini ? \n Le Patient Zéro n'était donc pas l'ennemi final...\n Regarde ! Quelqu'un approche...un pangolin ? Mais oui c'est lui le responsable.  \n\n ")
    print(Pangolin.nom, "PV :", Pangolin.pv,"\n",Pangolin.attack)
    while Pangolin.pv > 0 :
        print("\n\nLe Pangolin s'apprete a t'attaquer avec : ")
        Pango()
        print("\n Que veux-tu faire ?\n [1] Coup de poing\n [2] Gel hydroalcoolique 50%\n [3] Gel hydroalcoolique 100%\n [4] Vaccin\n [5] Fourmis")
        choice = int(input())
        if choice == 1 :
            Pangolin.pv = Pangolin.pv - arme.pangolincoup
            print("PV ennemi :", Pangolin.pv,"\nTon attaque n'est pas efficace, il a reussit à te toucher")
            joueur.pv = joueur.pv - degat.pangolinroulade
            print("tes PV :",joueur.pv)
        if choice == 2 : 
            Pangolin.pv =Pangolin.pv - arme.patientgel
            print("PV ennemi :", Pangolin.pv, "\nCette attaque n'est pas efficace, il a reussit à te toucher")
            joueur.pv = joueur.pv - degat.pangolinmorsure
            print("tes PV :",joueur.pv)
        if choice == 3 :
            Pangolin.pv = Pangolin.pv - arme.pangolingel1
            print("PV ennemi :", Pangolin.pv, "\nCette attaque n'est pas efficace, ")
            joueur.pv = joueur.pv - degat.pangolingriffure
            print("tes PV :",joueur.pv)
        if choice == 4 :
            Pangolin.pv = Pangolin.pv - arme.pangolinvaccin
            print("PV ennemi :", Pangolin.pv, "\n Cette attaque n'est pas efficace, tu ne peux pas le vacciner comme ca")
            print("Malgré son apparance infrangible, le Pangolin est un animal que l'ont peut dompter, c'est un petit mammifère qui se nourrit de fourmis et termites.\n Pas tres redoutable n'est-ce pas? Une fois apprivoisé c'est une bête très douce ")
        if choice == 5 :
            Pangolin.pv = Pangolin.pv - arme.pangolinfourmis
            print("Le Pangolin s'est calmé.\n Que veux-tu faire ? [1] Frapper [2] Amadouer\n")
            fourm = int(input())
            if fourm == 1 :
                print("Tu n'a infligé aucun dégat au pangolin")
                print("Le Pangolin s'est calmé.\n Que veux-tu faire ? [1] Frapper [2] Amadouer\n")
                ama = int(input())
                if ama == 2 :
                    print("Le Pangolin est devenu docile.\n Que veux-tu faire ? [1] Capturer et soigner [2] Tuer\n")
                    cap = int(input())
                    if cap == 1 :
                       print("Tu as gagné ! \nEn effet, devenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
                    if cap == 2 :
                       print("Tu as perdu...\nDevenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
                if ama == 1 :
                    print("Tu as perdu...\nDevenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
            if fourm == 2 :
                print("Le Pangolin est devenu docile.\n Que veux-tu faire ? [1] Capturer et soigner [2] Tuer\n")
                tue= int(input())
                if tue == 1 :
                    print("Tu as gagné ! \nEn effet, devenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
                if tue == 2 :
                    print("Tu as perdu...\nDevenu mondialement célèbre pour son rôle probable dans la transmission du coronavirus responsable de la pandémie de Covid-19, le pangolin connaît depuis des décennies un braconnage intense le menaçant d’extinction.\nLe pangolin, est un inoffensif mammifère poussé vers l’extinction par la gloutonnerie et la cupidité humaines. Il est le plus touché par le commerce illégal dans le monde.\n (pas la peine de tout lire c'est copié collé d'un article de ifaw.org) \nSi, avec leur armure, ces petites créatures occupaient autrefois de vastes territoires d’Asie et d’Afrique, leur nombre a aujourd’hui chuté de manière dramatique \nen raison de la demande massive et croissante pour leurs écailles auxquelles la médecine d’Asie du Sud-est prête des vertus curatives mais aussi pour leur chair, symbole d’un statut social élevé.\n« Les pangolins sont la proie du prédateur le plus dangereux : l’homme ».\n« Le rythme auquel les pangolins sont chassés est sans précédent et non durable pour l’espèce. La valeur que nous accordons à cet animal devrait uniquement refléter leur rôle dans leur milieu naturel et ne pas exprimer un statut social.\n Nous avons remporté des batailles acharnées afin de protéger cette espèce exotique, mais il reste encore tant à faire pour ne pas assister à son extinction. »\n")
        if joueur.pv <= 0 : 
            print("tu as été infecté, ta mission s'arrête là.")
            import time
            time.sleep(3)
            quit() 

nom = str(input())
Coronaventure(nom)


# Menudujeu 
x = 2
y = 3
i = 0
compteur = 0
Fin_Marseille = 0
Fin_Paris = 0
Fin_Londres = 0
Fin_Stockholm = 0
Fin_CDG = 0
Fin_Washington = 0
Fin_LosAngeles = 0
Fin_Cancun = 0
Fin_Rome = 0
Fin_Taiwan = 0
Fin_Shanghai = 0
Fin_Wuhan = 0
Game = Gameisnotfinished(0)

while Game == True:
  Marseille(Fin_Marseille)
  while i < 1000:
    Mouv = Deplacement(x,y)
    x = ResultatX(x,y,Mouv)
    y = ResultatY(x,y,Mouv)
    i = i + 1

    Fin_Marseille = Fin_Marseille + 1
    
    Event(nom,x,y,Fin_Marseille,Fin_Paris,Fin_Londres,Fin_Stockholm,Fin_CDG,Fin_Washington,
    Fin_LosAngeles,Fin_Cancun,Fin_Rome,Fin_Taiwan,Fin_Shanghai,Fin_Wuhan)

    if x == 2 and y == 2:
      Fin_Paris = Fin_Paris + 1
    elif x == 2 and y == 1:
      Fin_Londres = Fin_Londres + 1
    elif x == 3 and y == 1:
      Fin_Stockholm = Fin_Stockholm + 1
    elif x == 3 and y == 2:
      Fin_CDG = Fin_CDG + 1
    elif x == 1 and y == 1:
      Fin_Washington = Fin_Washington + 1
    elif x == 1 and y == 2:
      Fin_LosAngeles = Fin_LosAngeles + 1
    elif x == 1 and y == 3:
      Fin_Cancun = Fin_Cancun + 1
    elif x == 3 and y == 3:
      Fin_Rome = Fin_Rome + 1
    elif x == 4 and y == 3:
      Fin_Taiwan = Fin_Taiwan + 1
    elif x == 4 and y == 2:
      Fin_Shanghai = Fin_Shanghai + 1
    elif x == 4 and y == 1:
      Fin_Wuhan = Fin_Wuhan + 1

